ignore = [
    # compiler runtime / library symbols (provided by libgcc + libogg at link)
    "__udivdi3",
    "__umoddi3",
    "ogg_stream_flush_fill",
]

[extra_units]
ogg_vorbis = [
    "oggpackB_reset",
    "oggpack_reset",
    "ogg_sync_reset",
    "ogg_stream_reset_serialno",
    "ogg_stream_reset",
    "ov_bitrate",
    "ov_bitrate_instant",
    "ov_clear",
    "ov_comment",
    "ov_crosslap",
    "ov_fopen",
    "ov_halfrate",
    "ov_halfrate_p",
    "ov_info",
    "ov_open",
    "ov_open_callbacks",
    "ov_pcm_seek",
    "ov_pcm_seek_lap",
    "ov_pcm_seek_page",
    "ov_pcm_seek_page_lap",
    "ov_pcm_tell",
    "ov_pcm_total",
    "ov_raw_seek",
    "ov_raw_seek_lap",
    "ov_raw_tell",
    "ov_raw_total",
    "ov_read",
    "ov_read_filter",
    "ov_read_float",
    "ov_seekable",
    "ov_serialnumber",
    "ov_streams",
    "ov_test",
    "ov_test_callbacks",
    "ov_test_open",
    "ov_time_seek",
    "ov_time_seek_lap",
    "ov_time_seek_page",
    "ov_time_seek_page_lap",
    "ov_time_tell",
    "ov_time_total",

    "_Z12ov_time_seekP14OggVorbis_Filed",
    "_Z11ov_pcm_seekP14OggVorbis_Filex",
    "_Z17ov_open_callbacksPvP14OggVorbis_FilePKcl12ov_callbacks",
    "_Z7ov_infoP14OggVorbis_Filei",
    "_Z12ov_pcm_totalP14OggVorbis_Filei",
    "_Z13ov_time_totalP14OggVorbis_Filei",
    "_Z8ov_clearP14OggVorbis_File",
    "_Z7ov_readP14OggVorbis_FilePciiiiPi",
    "_Z11ov_raw_seekP14OggVorbis_Filex",
    "_Z13ov_halfrate_pP14OggVorbis_File",
    "_Z17ov_test_callbacksPvP14OggVorbis_FilePKcl12ov_callbacks",
    "_Z7ov_testP7__sFILEP14OggVorbis_FilePKcl",
    "_Z10ov_streamsP14OggVorbis_File",
    "_Z11ov_seekableP14OggVorbis_File",
    "_Z18ov_bitrate_instantP14OggVorbis_File",
    "_Z15ov_serialnumberP14OggVorbis_Filei",
    "_Z12ov_raw_totalP14OggVorbis_Filei",
    "_Z12ov_test_openP14OggVorbis_File",
    "_Z7ov_openP7__sFILEP14OggVorbis_FilePKcl",
    "_Z8ov_fopenPKcP14OggVorbis_File",
    "_Z16ov_pcm_seek_pageP14OggVorbis_Filex",
    "_Z11ov_halfrateP14OggVorbis_Filei",
    "_Z17ov_time_seek_pageP14OggVorbis_Filed",
    "_Z10ov_bitrateP14OggVorbis_Filei",
    "_Z11ov_raw_tellP14OggVorbis_File",
    "_Z11ov_pcm_tellP14OggVorbis_File",
    "_Z12ov_time_tellP14OggVorbis_File",
    "_Z10ov_commentP14OggVorbis_Filei",
    "_Z14ov_read_filterP14OggVorbis_FilePciiiiPiPFvPPfllPvES5_",
    "_Z13ov_read_floatP14OggVorbis_FilePPPfiPi",
    "_Z11ov_crosslapP14OggVorbis_FileS0_",
    "_Z15ov_raw_seek_lapP14OggVorbis_Filex",
    "_Z15ov_pcm_seek_lapP14OggVorbis_Filex",
    "_Z20ov_pcm_seek_page_lapP14OggVorbis_Filex",
    "_Z16ov_time_seek_lapP14OggVorbis_Filed",
    "_Z21ov_time_seek_page_lapP14OggVorbis_Filed",
]
