#include "legoapi/gameobject.h"

#define EMPTY_ANIMATION(name) \
    void name(GameObject_s *) {}

EMPTY_ANIMATION(Animate_ASTROMECH)
EMPTY_ANIMATION(Animate_ATAT)
EMPTY_ANIMATION(Animate_BARMAN)
EMPTY_ANIMATION(Animate_BATTLEDROID)
EMPTY_ANIMATION(Animate_BEAST)
EMPTY_ANIMATION(Animate_CANNON)
EMPTY_ANIMATION(Animate_CHARACTER)
EMPTY_ANIMATION(Animate_CRITTER)
EMPTY_ANIMATION(Animate_DEFAULT)
EMPTY_ANIMATION(Animate_DROIDEKA)
EMPTY_ANIMATION(Animate_GEONOSIAN)
EMPTY_ANIMATION(Animate_HOVERDROID)
EMPTY_ANIMATION(Animate_JEDI)
EMPTY_ANIMATION(Animate_POD)
EMPTY_ANIMATION(Animate_PROTOCOL)
EMPTY_ANIMATION(Animate_REPUBLICGUNSHIP)
EMPTY_ANIMATION(Animate_SPEEDERBIKE)
EMPTY_ANIMATION(Animate_SUPERBATTLEDROID)
EMPTY_ANIMATION(Animate_VEHICLE)
EMPTY_ANIMATION(Animate_WALKER)
EMPTY_ANIMATION(Animate_WEIRDO)
EMPTY_ANIMATION(PostAnimate_ASTROMECH)
EMPTY_ANIMATION(PostAnimate_FETT)

#undef EMPTY_ANIMATION

void AutoWeaponOnOff(GameObject_s *) {}
void CharShadows_Reset(PLAYERPACKET_s *) {}
