#include "legoapi/gameobject.h"
#include "nu2api/nu3d/nurndr.h"

i32 LEGOCONTEXT_BEENTAKENOVER;
i32 LEGOCONTEXT_BUILDIT;
i32 LEGOCONTEXT_DOOMED;
i32 LEGOCONTEXT_EATEN;
i32 LEGOCONTEXT_GETIN;
i32 LEGOCONTEXT_GLIDE;
i32 LEGOCONTEXT_GRAPPLE;
i32 LEGOCONTEXT_LAND_COMBOJUMP;
i32 LEGOCONTEXT_TUBE;
i16 LEGOACT_COMBOLAND;

u32 GAMEPAD_ACTION;
u32 GAMEPAD_JUMP;
f32 SLAMJUMPSPEED;
f32 MAGNETOFFSET;
f32 ForceThrowGravity;
i32 ForcePush_SuperPush;
f32 TURNTIME;
f32 TOGGLEHOLDTIME;
f32 DEFAULT_MOVE_RANGE;
f32 DEFENDTIME;
u8 BladeTab[1];
u8 Default_ADDPART[200];
u8 grapple_attach_frames;
u8 Cheat[0x200];
NUCOLOUR3 flashCol;

extern "C" u16 AnimMiscFlags(CHARACTERDATA *, i32) {
    return 0;
}
