#ifndef LEGOAPI_TYPES_H
#define LEGOAPI_TYPES_H
#pragma once

#include "nu2api/nucore/fixed_width.h"

#include "legoapi/items/base/apiobject.h"
#include "MechInputTouch/MechInputTouch_types.h"
#include "legoapi/characters/core/CharacterObjectInterface.h"
#include "legoapi/gizmo/base/GizBlowupObjectInterface.h"
#include "legoapi/gizmo/base/GizBuildItObjectInterface.h"
#include "legoapi/gizmo/base/GizForceObjectInterface.h"
#include "legoapi/gizmo/base/GizLeverObjectInterface.h"
#include "legoapi/gizmo/base/GizObstacleObjectInterface.h"
#include "legoapi/gizmo/base/GizPanelObjectInterface.h"
#include "legoapi/gizmo/base/GizTurretObjectInterface.h"
#include "legoapi/gizmo/base/HatMachineObjectInterface.h"
#include "legoapi/gizmo/base/TeleportObjectInterface.h"
#include "legoapi/render/core/SwipeDecalRenderer.h"

struct ADDGAMEMSG;
struct ADDPART_s;
struct AIANTINODE_s;
struct AIAREA_s;
struct AIGROUP_s;
struct AILOCATOR_s;
struct AIPACKET_s;
struct AIPATHCNXCONTROLLER_s;
struct AIPATHCNXCONTROLSYS_s;
struct AIPATHCNXHELPERSYS_s;
struct AIPATHCNXHELPER_s;
struct AIPATHCNX_s;
struct AIPATHINFO_s;
struct AIPATHNODE_s;
struct AIPATH_s;
struct AISCRIPTPROCESS_s;
struct AISCRIPT_s;
struct AISYS_s;
struct AITRIGGERSETSYS_s;
struct AITRIGGERSET_s;
struct ANIMLIST_s;
struct ANIMPACKET_s;
struct ANIMREDIRECT;
struct APICHARACTERMODELLIST_s;
struct APIOBJECT_s;
struct AREADATA_s;
struct AREASAVE_s;
struct ATTRACTO_s;
struct BATARANG_s;
struct BOLTSYS;
struct BOLT_s;
struct BUILDIT_FIND_ENUM;
struct BaseEditor;
struct BaseThing;
struct CABLE_s;
struct CHARACTERDATA_s;
struct CHARACTERMODEL_s;
struct CHARCATEGORY;
struct CHARFIXUP;
struct CHARPIVOT;
struct CHARPLATFORMSYS_s;
struct CHARVARIANT;
struct CHEAT;
struct CLIMBOBJECTSYS_s;
struct COINPACKET_s;
struct COLLECTION_s;
struct CUSTOMISER;
struct CUSTOMISESAVE_s;
struct CUSTOMPIECE;
struct CUTINFO;
struct CUTSCENESYS;
struct CUTSYS;
struct CantPickupBombTimerAddon;
struct CharacterObjectInterface;
struct ClassEditor;
struct ClassItem;
struct ClassObject;
struct ClassObjectList;
struct ClickToPressStartGestureTracker;
struct CursorTool;
struct DATAPTR;
struct DETONATOR_s;
struct DOOR_s;
struct EDCREATURE_s;
struct EPISODEDATA;
struct EXPLOSION;
struct EXTRAMODEL;
struct EdClass;
struct EdControl;
struct EdFileInputStream;
struct EdFileOutputStream;
struct EdInputContext;
struct EdRef;
struct EdStream;
struct EdTool;
struct FADEINFO_s;
struct FADETYPE;
struct FLOWBOX_s;
struct FS_FILEENTRYHDR;
struct Fade;
struct FadeBase;
struct FadeStill;
struct FadeStillWipe;
struct FadeSystem;
struct FadeWipe;
struct GAMEANIMOBJPOOL_s;
struct GAMEANIMOBJ_s;
struct GAMEANIMSET_s;
struct GAMEANIMSYS_s;
struct GAMEANTINODEDATA_s;
struct GAMEANTINODESYS_s;
struct GAMEANTINODE_s;
struct GAMEAUDIO;
struct GAMECAMERA_s;
struct GAMECHARACTERDATA_s;
struct GAMEMESSAGE_s;
struct GAMEPAD_s;
struct GIZACTIONDEFN_s;
struct GIZAIMESSAGESYS_s;
struct GIZAIMESSAGE_s;
struct GIZBOMBGENSYS_s;
struct GIZBUILDIT_s;
struct GIZFLOWPROGRESS_s;
struct GIZFLOW_s;
struct GIZFORCESYS_s;
struct GIZFORCE_s;
struct GIZMOBLOWUPTYPE_s;
struct GIZMOBLOWUP_s;
struct GIZMOPICKUPSYS_s;
struct GIZMOPICKUP_s;
struct GIZMOSYS_s;
struct GIZMO_s;
struct GIZOBSTACLESYS_s;
struct GIZOBSTACLE_s;
struct GIZPANEL_s;
struct GIZSPECIAL_s;
struct GIZSPINNER_s;
struct GIZTURRETSYS_s;
struct GIZTURRET_s;
struct GRABBER_s;
struct GRAPPLE_s;
struct GameObject_s;
struct GameThingManager;
struct GizBlowupObjectInterface;
struct GizBuildItObjectInterface;
struct GizForceObjectInterface;
struct GizLeverObjectInterface;
struct GizObstacleObjectInterface;
struct GizPanelObjectInterface;
struct GizTurretObjectInterface;
struct HATMACHINE_s;
struct HINT_s;
struct HOTHBATTLE_MELEE_s;
struct HashRedirect;
struct HashedKey;
struct HatMachineObjectInterface;
struct HudRadarPulse;
struct LANGUAGEDATA;
struct LEVELDATADISPLAY;
struct LEVELDATA_s;
struct LEVELOBJECT;
struct LEVELSCRIPTPROCESS_s;
struct LEVELSPLINE;
struct LEVEL_PROGRESS_s;
struct LEVER_s;
struct LevelEditor;
struct LoadedUniqueShaderRecord;
struct MENU_s;
struct MISSIONSAVE_s;
struct MISSIONSYS_s;
struct MechAddon;
struct MechInputTouchMainController;
struct MechInputTouchVirtualConsoleController;
struct MechObjectInterface;
struct MechTouchUIElement;
struct MemoryBuffer;
struct MemoryManager;
struct MoveToMarker;
struct NARROWSOCKEXCEPTION;
struct NUGCUTCHAR_s;
struct NUGCUTSCENE_s;
struct NetAddress;
struct NetMessage;
struct NetPeer;
struct NuBloomParameters;
struct NuShaderObject;
struct NuShaderUsageMask_s;
struct NuVec2;
struct OPTIONSSAVE_s;
struct OccluderSet;
struct OcclusionManager;
struct OggVorbis_File;
struct PARTDEBSYS_s;
struct PART_s;
struct PLATSKININFO;
struct PLAYERITEMTYPE_s;
struct PLAYERITEM_s;
struct PLAYERPACKET_s;
struct PLUGSYS_s;
struct PLUG_s;
struct PULSESYS_s;
struct PartHeader;
struct PartObjectInterface;
struct Placeable;
struct PlaceableHelper;
struct PlaceableInterface;
struct PlaceableNameControl;
struct PropertyMenu;
struct PropertyMenuList;
struct PropertyTool;
struct REGISTERSTATUSPACKET_s;
struct RGBA;
struct RUMBLEPACKET;
struct SCENEPROGRESS_s;
struct SHADERSEMANTIC_enum;
struct SHARD_s;
struct SOCKPOSITION_s;
struct SOCKSYS;
struct SPLINEPOS_s;
struct STATUSPACKET_s;
struct STATUS_STAGE_s;
struct SUIT_s;
struct SUPERCOUNTER;
struct SUPERCOUNTERPICKUP;
struct SceneInstance;
struct SceneObject;
struct SceneObjectHelper;
struct ShaderManagerOpenGL;
struct ShaderMtlDescFilter;
struct ShaderObjectKey;
struct SoundTable;
struct SpecialObject;
struct SwipeDecalRenderer;
struct TECHNO_s;
struct TELEPORT_s;
struct TERRPICKUPSET;
struct TERRSET;
struct TEXTCRAWL_s;
struct TEXTENTRY;
struct TMClient;
struct TORPEDOPACKET_s;
struct TRAFFICANIMSYS_s;
struct TTNetwork;
struct TUBE_s;
struct TeleportObjectInterface;
struct ThingLevelData;
struct ThingManager;
struct ThingProcessData;
struct ThingRemoveData;
struct ThingRenderData;
struct ThingResetData;
struct TouchHolder;
struct VirtualControlButton;
struct VirtualControlButtonMover;
struct VirtualControlDPad;
struct VirtualControlDPad_LockButton;
struct VirtualStackAllocator;
struct VuMtx;
struct VuVec;
struct WORLDINFO_s;
struct __sFILE;
struct _vum_s;
struct _vuv_s;
struct ani3_animheader_s;
struct ani3_scalemin_s;
struct bgprocinfo_s;
struct bitrate_manager_state;
struct codebook;
struct debinftype;
struct debkeydatatype_s;
struct debris_chunk_control_s;
struct drft_lookup;
struct edcam_s;
struct eduiitem_s;
struct eduimenu_s;
struct envelope_lookup;
struct flightspline_s;
struct instNUGCUTLOOKAT_s;
struct instNUGCUTSCENE_s;
struct mdct_lookup;
struct minisnowtrooper_s;
struct minitrooperteam_s;
struct nuanimbuff_s;
struct nucolour3_s;
struct nudisplaylistitem_s;
struct nudisplayscene_s;
struct nufile_device_s;
struct nufpar_s;
struct nufpcomjmp_s;
struct nuglobalrndrstate_s;
struct nugraph_s;
struct nugscn_s;
struct nugspline_s;
struct nuhspecial_s;
struct nuinstanim_s;
struct numtl_s;
struct numtx_s;
struct nunativedebrisdata_s;
struct nuoctreenode_s;
struct nupad_s;
struct nushadermtldesc_s;
struct nusound_filename_info_s;
struct nutex_s;
struct nutexmanager_s;
struct nuvec_s;
struct ogg_packet;
struct oggpack_buffer;
struct ov_callbacks;
struct particlechunkrendertype_s;
struct pushblock_s;
struct ripple_node_s;
struct ripple_set_s;
struct rtldata_s;
struct rtlset;
struct shopitem_s;
struct specialsfx_s;
struct speedup_s;
struct starfighter_s;
struct static_codebook;
struct terrsitu_s;
struct tertype;
struct uv1deb;
struct uv1debdata;
struct vorbis_block;
struct vorbis_comment;
struct vorbis_dsp_state;
struct vorbis_info;
struct vorbis_info_mapping0;
struct vorbis_info_psy;
struct vorbis_info_psy_global;
struct vorbis_look_floor1;
struct vorbis_look_psy;
struct vorbis_look_psy_global;
struct vucharidx_s;

struct ADDGAMEMSG {};
struct ADDPART_s {};
struct AIANTINODE_s;
struct AIAREA_s;
struct AIGROUP_s;
struct AILOCATOR_s;
struct AIPACKET_s;
struct AIPATHCNXCONTROLLER_s {};
struct AIPATHCNXCONTROLSYS_s {};
struct AIPATHCNXHELPERSYS_s {};
struct AIPATHCNXHELPER_s {};
struct AIPATHINFO_s;
struct AIPATHNODE_s;
struct AISCRIPTPROCESS_s;
struct AISCRIPT_s;
struct AITRIGGERSETSYS_s {};
struct AITRIGGERSET_s {};
struct ANIMLIST_s {};
struct ANIMPACKET_s {};
struct ANIMREDIRECT {};
struct APICHARACTERMODELLIST_s {
    i16 model_list[];
};
struct AREADATA_s;
struct AREASAVE_s {};
struct ATTRACTO_s;
struct BATARANG_s {};
struct BOLTSYS {};
struct BOLT_s;
struct BUILDIT_FIND_ENUM {};
struct CABLE_s {};
struct CHARACTERDATA_s {};
struct CHARACTERMODEL_s {};
struct CHARCATEGORY {};
struct CHARFIXUP {};
struct CHARPIVOT {};
struct CHARPLATFORMSYS_s {};
struct CHARVARIANT {};
struct CHEAT;
struct CLIMBOBJECTSYS_s {};
struct COINPACKET_s {};
struct CUSTOMISER {};
struct CUSTOMISESAVE_s {};
struct CUSTOMPIECE {};
struct CUTINFO {};
struct CUTSCENESYS {};
struct CUTSYS {};
struct ClassItem {};
struct DETONATOR_s {};
struct EDCREATURE_s {};
struct EPISODEDATA;
struct EXPLOSION {};
struct EXTRAMODEL {};
struct EdClass;
struct EdControl;
struct EdFileInputStream;
struct EdFileOutputStream;
struct EdInputContext;
struct EdRef;
struct EdStream;
struct EdTool {};
struct FADEINFO_s {};
struct FADETYPE {};
struct FLOWBOX_s {};
struct FS_FILEENTRYHDR {};
struct FadeBase {};
struct GAMEANIMOBJPOOL_s {};
struct GAMEANIMOBJ_s {};
struct GAMEANIMSET_s {};
struct GAMEANIMSYS_s {};
struct GAMEANTINODEDATA_s {};
struct GAMEANTINODESYS_s {};
struct GAMEANTINODE_s {};
struct GAMEAUDIO {};
struct GAMECAMERA_s {};
struct GAMECHARACTERDATA_s {};
struct GAMEMESSAGE_s {};
struct GAMEPAD_s {};
struct GIZACTIONDEFN_s {};
struct GIZAIMESSAGESYS_s {};
struct GIZAIMESSAGE_s;
struct GIZBOMBGENSYS_s {};
struct GIZFLOWPROGRESS_s {};
struct GIZFLOW_s {};
struct GIZFORCESYS_s {};
struct GIZMOBLOWUPTYPE_s {};
struct GIZMOPICKUPSYS_s {};
struct GIZMOPICKUP_s;
struct GIZMOSYS_s;
struct GIZMO_s;
struct GIZOBSTACLESYS_s {};
struct GIZSPECIAL_s;
struct GIZSPINNER_s {};
struct GIZTURRETSYS_s {};
struct GRABBER_s {};
struct GRAPPLE_s;
struct HINT_s {};
struct HOTHBATTLE_MELEE_s {};
struct HashRedirect {};
struct HashedKey {};
struct LANGUAGEDATA {};
struct LEVELDATADISPLAY {};
struct LEVELDATA_s;
struct LEVELOBJECT {};
struct LEVELSCRIPTPROCESS_s;
struct LEVELSPLINE {};
struct LoadedUniqueShaderRecord {};
struct MENU_s;
struct MISSIONSAVE_s;
struct MemoryBuffer;
struct NARROWSOCKEXCEPTION {};
struct NUGCUTCHAR_s;
struct NUGCUTSCENE_s;
struct NetAddress;
struct NetMessage;
struct NetPeer;
struct NuBloomParameters {};
struct NuShaderObject {};
struct NuShaderUsageMask_s {};
struct OPTIONSSAVE_s;
struct OggVorbis_File {};
struct PARTDEBSYS_s {};
struct PLATSKININFO {};
struct PLAYERITEMTYPE_s {};
struct PLAYERITEM_s {};
struct PLAYERPACKET_s {};
struct PLUGSYS_s {};
struct PLUG_s;
struct PULSESYS_s {};
struct PartHeader;
struct PropertyMenuList {};
struct REGISTERSTATUSPACKET_s {};
struct RGBA {};
struct RUMBLEPACKET {};
struct SCENEPROGRESS_s {};
struct SHADERSEMANTIC_enum {};
struct SHARD_s;
struct SOCKPOSITION_s {};
struct SOCKSYS {};
struct SPLINEPOS_s {};
struct STATUSPACKET_s {};
struct STATUS_STAGE_s {};
struct SUIT_s {};
struct SUPERCOUNTER {};
struct SUPERCOUNTERPICKUP {};
struct ShaderObjectKey;
struct SoundTable {};
struct TECHNO_s;
struct TERRPICKUPSET {};
struct TERRSET {};
struct TEXTCRAWL_s {};
struct TEXTENTRY {};
struct TORPEDOPACKET_s {};
struct TRAFFICANIMSYS_s {};
struct TUBE_s;
struct ThingLevelData {};
struct ThingRemoveData {};
struct VirtualStackAllocator;
struct VuMtx;
struct __sFILE {};
struct _vum_s {};
struct _vuv_s;
struct ani3_animheader_s;
struct ani3_scalemin_s {};
struct bgprocinfo_s;
struct bitrate_manager_state {};
struct codebook {};
struct debinftype {};
struct debkeydatatype_s {};
struct debris_chunk_control_s {};
struct drft_lookup {};
struct edcam_s {};
struct eduiitem_s;
struct eduimenu_s;
struct envelope_lookup {};
struct flightspline_s {};
struct instNUGCUTLOOKAT_s {};
struct instNUGCUTSCENE_s {};
struct mdct_lookup {};
struct minisnowtrooper_s {};
struct minitrooperteam_s {};
struct nuanimbuff_s;
struct nucolour3_s;
struct nudisplaylistitem_s;
struct nudisplayscene_s;
struct nufile_device_s;
struct nufpar_s;
struct nufpcomjmp_s;
struct nuglobalrndrstate_s {};
struct nugraph_s {};
struct nugscn_s;
struct nugspline_s;
struct nuhspecial_s;
struct nuinstanim_s {};
struct numtl_s;
struct numtx_s;
struct nunativedebrisdata_s {};
struct nuoctreenode_s {};
struct nupad_s;
struct nushadermtldesc_s;
struct nusound_filename_info_s;
struct nutex_s;
struct nutexmanager_s {};
struct ogg_packet {};
struct oggpack_buffer {};
struct ov_callbacks {};
struct particlechunkrendertype_s {};
struct pushblock_s {};
struct ripple_node_s {};
struct ripple_set_s {};
struct rtldata_s {};
struct rtlset {};
struct shopitem_s {};
struct specialsfx_s {};
struct speedup_s {};
struct starfighter_s {};
struct static_codebook {};
struct terrsitu_s {};
struct tertype {};
struct uv1deb {};
struct uv1debdata;
struct vorbis_block {};
struct vorbis_comment {};
struct vorbis_dsp_state {};
struct vorbis_info {};
struct vorbis_info_mapping0 {};
struct vorbis_info_psy {};
struct vorbis_info_psy_global {};
struct vorbis_look_floor1 {};
struct vorbis_look_psy {};
struct vorbis_look_psy_global {};
struct vucharidx_s {};

struct BaseEditor {
    void Initialise(variptr_u &, variptr_u &, i32);
    void ReadBuffer(void **, void *, i32);
    void WriteBeginBlock(i32, i32);
    void WriteEndBlock(i32);
    void WriteMetaData(i32, i32, i32, i32);
};
struct BaseThing {
    BaseThing();
    virtual ~BaseThing();
};
struct CantPickupBombTimerAddon {
    CantPickupBombTimerAddon(MechObjectInterface &, float);
    void OnProcess(MechAddon::ProcessStage, float);
    virtual ~CantPickupBombTimerAddon();
};

struct ClassEditor {
    ClassEditor();
    void AddMenuItems(eduimenu_s *);
    void ClearLevel(i32);
    void CreateObject();
    void CreateObject(ClassObject &);
    void CreateObject(EdClass *);
    void CreateObject(i32);
    void DestroySelectedObjects();
    void DestroySelectedObjectsNow();
    void DrawObjectSphere(ClassObject &, i32);
    void Editable(void *, EdClass *, i32);
    void Enter();
    void Exit();
    void FindNearestObject(VuVec &, ClassObject &, ClassObject &, i32);
    void FindNearestObject(VuVec &, ClassObject &, i32);
    void FindNearestObject(VuVec &, VuVec &, ClassObject &, ClassObject &, i32);
    void FindNearestObject(VuVec &, VuVec &, ClassObject &, i32);
    void Flush();
    void FocusSelected();
    void Initialise(variptr_u &, variptr_u &, i32);
    void InitialiseObject(ClassObject &);
    void IsSelectedClass(EdClass *);
    void IsSelectedObject(ClassObject &);
    void IsSelectedObject(void *, EdRef *);
    void IsUniqueName(char *);
    void MakeUniqueName(char const *, char *, i32);
    void PostLoadInitialisation(MemoryBuffer *, MemoryBuffer *);
    void PostSaveInitialisation();
    void PreLoadInitialisation(MemoryBuffer *, MemoryBuffer *);
    void PreSaveInitialisation();
    void Process(EdInputContext &);
    void ReadBlock(DATAPTR *);
    void RegisterTool(EdTool &);
    void Render();
    void SelectLED(i32);
    void SelectObject(ClassObject &, i32);
    void Serialise(EdStream &);
    void SetMode(i32);
    void SetViewMenuHilight(eduimenu_s *);
    void SnapPoint(VuVec &);
    void UpdateClassFilter(EdInputContext &);
    void UpdateLists(MemoryBuffer *, MemoryBuffer *);
    void UpdateSelectedObjects(EdInputContext &);
    void UpdateSnapRay(VuVec &);
    void ViewSelected();
    void WriteBlock(i32);
    void cbDestroyMenu(eduimenu_s *, eduimenu_s *);
    void cbDestroyObject(eduimenu_s *, eduiitem_s *, u32);
    void cbEdClassDeleteObject(eduimenu_s *, eduiitem_s *, u32);
    void cbEdClassExportMenu(eduimenu_s *, eduiitem_s *, u32);
    void cbEdClassFileMenu(eduimenu_s *, eduiitem_s *, u32);
    void cbEdClassImportMenu(eduimenu_s *, eduiitem_s *, u32);
    void cbEdClassModeMenu(eduimenu_s *, eduiitem_s *, u32);
    void cbEdClassNewMenu(eduimenu_s *, eduiitem_s *, u32);
    void cbEdClassNewObject(eduimenu_s *, eduiitem_s *, u32);
    void cbEdClassRemoveDuplicates(eduimenu_s *, eduiitem_s *, u32);
    void cbEdClassSelectClassMenu(eduimenu_s *, eduiitem_s *, u32);
    void cbEdClassSelectObject(eduimenu_s *, eduiitem_s *, u32);
    void cbEdClassSelectObjectMenu(eduimenu_s *, eduiitem_s *, u32);
    void cbEdClassSetMode(eduimenu_s *, eduiitem_s *, u32);
    void cbEdClassSetPinned(eduimenu_s *, eduiitem_s *, u32);
    void cbEdClassSetSnap(eduimenu_s *, eduiitem_s *, u32);
    void cbEdClassSetView(eduimenu_s *, eduiitem_s *, u32);
    void cbEdClassSnapMenu(eduimenu_s *, eduiitem_s *, u32);
    void cbEdClassToolsMenu(eduimenu_s *, eduiitem_s *, u32);
    void cbEdClassViewMenu(eduimenu_s *, eduiitem_s *, u32);
    void cbEdCopySelectedObject(EdInputContext &);
    void cbEdCreateClassNewObject(i32);
    void cbEdFilterLED(eduimenu_s *, eduiitem_s *, u32);
    void cbEdLevelDeselectAll(eduimenu_s *, eduiitem_s *, u32);
    void cbEdLevelSelectAll(eduimenu_s *, eduiitem_s *, u32);
    void cbEdPadSetManipulatorMode(eduimenu_s *, eduiitem_s *, u32);
    void cbFileSelected(eduimenu_s *, eduiitem_s *, u32);
};
struct ClassObject {
    void GetName(char *, i32);
    void Set(char *);
};
struct ClassObjectList {
    void GetAveragePosition(VuVec &);
    void GetAveragePosition(VuVec &, float &);
    void IsInList(ClassObject);
    void IsInList(EdClass *);
    void IsInList(void *, EdRef *);
};
struct ClickToPressStartGestureTracker {
    void OnClick(GameObject_s &, TouchHolder &);
};
struct CursorTool {
    void Initialise(variptr_u &, variptr_u &, i32);
    void Process(EdInputContext &);
    void Render();
};
struct Fade {
    void DrawFade();
    void Init(FADEINFO_s *);
    void InitFade();
    void UpdateFade();
};
struct FadeStill {
    void DrawFade();
    void Init(FADEINFO_s *);
    void InitFade();
    void UpdateFade();
};
struct FadeStillWipe {
    void DrawFade();
    void Init(FADEINFO_s *);
    void InitFade();
    void UpdateFade();
};
struct FadeSystem {
    void AddFade(FadeBase *);
    void Draw();
    void Init();
    void SetFade(FADETYPE const &, u32);
    void SetStage(char);
    void Update();
};
struct FadeWipe {
    void DrawFade();
    void Init(FADEINFO_s *);
    void InitFade();
    void UpdateFade();
};
struct GIZBUILDIT_s {
    void ClearMechObjectInterface();
    void GetMechObjectInterface();
};
struct GIZFORCE_s {
    void ClearMechObjectInterface();
    void GetMechObjectInterface();
};
struct GIZMOBLOWUP_s {
    void ClearMechObjectInterface();
    void GetMechObjectInterface();
};
struct GIZOBSTACLE_s {
    void ClearMechObjectInterface();
    void GetMechObjectInterface();
};
struct GIZPANEL_s {
    void ClearMechObjectInterface();
    void GetMechObjectInterface();
};
struct GIZTURRET_s {
    void ClearMechObjectInterface();
    void GetMechObjectInterface();
};
struct GameThingManager {
    void AddLevelOnlyThings();
    void AddOnceOnlyThings();
    GameThingManager(i32);
    virtual ~GameThingManager();
};
struct HATMACHINE_s {
    void ClearMechObjectInterface();
    void GetMechObjectInterface();
};
struct HudRadarPulse {
    HudRadarPulse(VuVec const &);
    void IsFinished();
    void Process(float);
    void Render();
};
struct LEVER_s {
    void ClearMechObjectInterface();
    void GetMechObjectInterface();
};
struct LevelEditor {
    void AddInfoText(char *);
    void AddScene(char *, nugscn_s *, i32);
    void AddText(char *);
    void BeginMultiLoad(variptr_u *, variptr_u *);
    void ClearLevel(i32);
    void CloseMenu();
    void CreateEditorList(eduimenu_s *, eduiitem_s *);
    void CreateMenu();
    void Display(ThingRenderData *);
    void DrawInfoText(char **, i32, i32, i32, i32, i32, i32, i32);
    void EndMultiLoad(variptr_u *, variptr_u *);
    void Enter();
    void Exit();
    void FindSceneId(char *);
    void Flush();
    void GetEdScene(i32);
    void GetScene(char *);
    void GetScene(i32);
    void Initalise(variptr_u &, variptr_u &, i32);
    void IsActiveScene(nugscn_s *);
    void IsEditable(i32);
    LevelEditor();
    void Load(char *, variptr_u *, variptr_u *, i32);
    void LoadState(variptr_u *, variptr_u *, variptr_u *, variptr_u *, variptr_u *, variptr_u *);
    void ProcessEvenWhenPaused(ThingProcessData *);
    void ReadStream(EdFileInputStream &);
    void RegisterEditor(BaseEditor &);
    void Reset();
    void Save();
    void SaveState(i32, variptr_u *, variptr_u *);
    void SaveState(variptr_u *, variptr_u *);
    void SetNextMenu(eduimenu_s *);
    void SetPadText(i32, char *);
    void SetSaveFilename(char *);
    void WriteStream(EdFileOutputStream &);
};
struct MemoryManager {
    void AllocPool(u32, i32);
    void FreePool(void *, u32);
};
struct MoveToMarker {
    void BlowUp();
    void FadeOut();
    MoveToMarker(MechObjectInterface &);
    void Process(float);
    void Render();
};
struct OccluderSet {
    void AddOccluder(nuvec_s const *, nuvec_s const *, nuvec_s const *, nuvec_s const *);
    void Clear();
    void Init(u32, variptr_u *, variptr_u);
    void IsOccludedOBB(nuvec_s const *, nuvec_s const *, numtx_s const *);
    void IsOccludedSphere(nuvec_s const *, float);
    OccluderSet();
    void OnCameraSet();
    void PrepareForQueries(numtx_s const *, numtx_s const *);
    void RenderOccluders(bool) const;
    void SortByDepth(void const *, void const *);
    ~OccluderSet();
};
struct OcclusionManager {
    void AddOccluder(nuvec_s const *, float);
    void AddOccluder(nuvec_s const *, nuvec_s const *, numtx_s const *);
    void AddOccluder(nuvec_s const *, nuvec_s const *, nuvec_s const *, nuvec_s const *);
    void BeginFrame();
    void EndFrame();
    void Init(u32, variptr_u *, variptr_u);
    void IsOccludedOBB(nuvec_s const *, nuvec_s const *, numtx_s const *);
    void IsOccludedSphere(nuvec_s const *, float);
    OcclusionManager();
    void OnCameraSet();
    void RenderStats() const;
    void RenderZPass() const;
    void SetEnabled(bool);
    ~OcclusionManager();
};
struct PART_s {
    void ClearMechObjectInterface();
    void GetMechObjectInterface();
};
struct PartObjectInterface {
    void GetPos(VuVec &, i32) const;
    void GetRadius() const;
    void GetTargetName() const;
    PartObjectInterface(PART_s &);
    virtual ~PartObjectInterface();
};
struct Placeable {
    void GetCurrentPosition() const;
    void GetInitialPosition() const;
    void SetCurrentPosition(VuVec const *);
    void SetInitialPosition(VuVec const *);
};
struct PlaceableHelper {
    void Find(char *);
    void Find(char *, Placeable **, i32);
    void FindObject(char *);
    void GetNextObject(void *);
    void GetNextObject(void *, i32 (*)(void *));
    void Initialise();
    void IsEditorObject(ClassObject &);
    PlaceableHelper();
    void RegisterObjectType(char *, PlaceableInterface *);
};
struct PlaceableInterface {
    void DebugOutputObjects();
    void Find(char *);
    void Find(char *, Placeable **, i32);
};
struct PlaceableNameControl {
    void AddMenuItem(eduimenu_s *, EdRef *, void *);
    PlaceableNameControl();
    void Process(EdInputContext &);
    void Render();
    void cbButton(eduimenu_s *, eduiitem_s *, u32);
    void cbChanged(eduimenu_s *, eduiitem_s *, u32);
    void cbSelectObject(eduimenu_s *, eduiitem_s *, u32);
};
struct PropertyMenu {
    void AddObject(ClassObject &);
    void ClearObjecs();
    void ContainsObject(ClassObject &);
    void ContainsObject(void *);
    void Destroy();
    void SelectAttr(i32);
};
struct PropertyTool {
    void AddPropertyMenuItems(eduimenu_s *, EdClass *, void *, eduiitem_s *);
    void AutoLocateMenu(PropertyMenu *);
    void BringToFront(PropertyMenu *);
    void CreatePropertyMenu(ClassObject &);
    void FindItemMenu(PropertyMenu *, ClassItem *);
    void GetActiveMenu(PropertyMenu *);
    void GetClassName(EdRef *, char *);
    void GetNextActiveMenu();
    void GetNextDefaultActiveMenu(eduimenu_s *);
    void GetTypeName(EdRef *, char *);
    void HasActiveMenu();
    void Initialise(variptr_u &, variptr_u &, i32);
    void Process(EdInputContext &);
    void ProcessControls(EdInputContext &);
    void ProcessMenu(EdInputContext &);
    PropertyTool();
    void RefreshMenuControls(PropertyMenu *);
    void Render();
    void RenderMenu(PropertyMenu *);
    void RetrievePropertyMenu(ClassObject *, PropertyMenuList *);
    void SelectAttr(i32);
    void SetDefaultActiveMenu(PropertyMenu *);
    void SetMenuControl(eduimenu_s *, EdControl *);
    void ToggleActiveMenu();
    void ediGetMenuStartMetrics();
    void ediMenuRetrieveMetrics(eduimenu_s *);
    void ediMenuStoreMetrics(eduimenu_s *);
};
struct SceneInstance {
    void GetCurrentPosition() const;
    void GetCurrentTransform() const;
    void GetInitialPosition() const;
    void GetInitialTransform() const;
    void GetVisibility() const;
    void Render(VuMtx const *) const;
    SceneInstance();
    void SetCurrentPosition(VuVec const *);
    void SetCurrentTransform(VuMtx const *);
    void SetInitialPosition(VuVec const *);
    void SetInitialTransform(VuMtx const *);
    void SetVisibility(i32);
};
struct SceneObject {
    void Clone(i32) const;
    SceneObject();
};
struct SceneObjectHelper {
    void AddMenuItems(eduimenu_s *);
    void ClearLevel(i32);
    void CreateObject(void *, i32, i32);
    void DestroyObject(void *, i32);
    void Flush();
    void GetNextObject(void *);
    void GetNumObjects();
    void Initialise();
    void PostLoadInitialisation(MemoryBuffer *, MemoryBuffer *);
    void PreLoadInitialisation(MemoryBuffer *, MemoryBuffer *);
    void SetSceneFilter(char *);
    void SubRender();
    void UpdateLists(MemoryBuffer *, MemoryBuffer *);
    void cbEdSceneObjectShowHiddenSolid(eduimenu_s *, eduiitem_s *, u32);
    void cbEdSceneObjectShowHiddenWire(eduimenu_s *, eduiitem_s *, u32);
    void cbEdSceneObjectShowOwnedObjects(eduimenu_s *, eduiitem_s *, u32);
};
struct ShaderManagerOpenGL {
    ShaderManagerOpenGL(VirtualStackAllocator &);
    void adaptShaderMaterialForShaderVersion(nushadermtldesc_s *);
    void createShader(ShaderMtlDescFilter &, bool, NuShaderObject *, i32);
    void createShader(ShaderObjectKey const &, NuShaderObject *, i32);
    void setElementfv(SHADERSEMANTIC_enum, i32, float const *);
    void setElementsfv(SHADERSEMANTIC_enum, i32, i32, float const *);
    void setElementsfv_transpose(SHADERSEMANTIC_enum, i32, i32, float const *);
    void setfv(SHADERSEMANTIC_enum, float const *);
    virtual ~ShaderManagerOpenGL();
};
struct ShaderMtlDescFilter {
    void getVertexFlags() const;
    void hasDiffuseMap(i32) const;
    void hasLayer(i32) const;
    void internalInit(nushadermtldesc_s const *, numtl_s const *, i32, i32);
};
struct SpecialObject {
    void Exists() const;
    void GetCollision() const;
    void GetCurrentPosition() const;
    void GetCurrentTransform() const;
    void GetInitialPosition() const;
    void GetInitialTransform() const;
    void GetMtl(i32) const;
    void GetName() const;
    void GetNumMtls() const;
    void GetRadius() const;
    void GetVisibility() const;
    void Render(VuMtx const *) const;
    void SetCollision(i32);
    void SetCurrentPosition(VuVec const *);
    void SetCurrentTransform(VuMtx const *);
    void SetInitialPosition(VuVec const *);
    void SetInitialTransform(VuMtx const *);
    void SetVisibility(i32);
    SpecialObject();
};
struct TELEPORT_s {
    void ClearMechObjectInterface();
    void GetMechObjectInterface();
};
struct TMClient {
    struct TM_MOUSE_AXIS {};
    void AllocHandle();
    void Connect();
    void FClose(i32);
    void FOpen(char const *, char const *);
    void FRead(void *, u32, u32, i32);
    void FSeek(i32, i64, i32);
    void FTell(i32);
    void FWrite(void const *, u32, u32, i32);
    void FlushKeyBuffer();
    void GetKey(i32 *);
    void GetMouseAxis(TMClient::TM_MOUSE_AXIS);
    void GetMouseButtons();
    void SendTTY(char const *, i32);
    void TestKey(i32);
};
struct TTNetwork {
    void Broadcast(NetMessage, unsigned char);
    void ClearMyHostAddress();
    void Display(ThingRenderData *);
    void GetMyAddress() const;
    void GetMyHostAddress() const;
    void Initialise();
    void ProcessEvenWhenPaused(ThingProcessData *);
    void ReliableBroadcast(NetMessage, unsigned char);
    void ReliableSend(NetMessage, unsigned char, NetPeer &, char const *, u32);
    void Resume();
    void Send(NetMessage, unsigned char, NetPeer &);
    void SetMyHostAddress(NetAddress const &);
    void Shutdown();
    void Suspend();
    TTNetwork();
    void Update();
    virtual ~TTNetwork();
};
struct ThingManager {
    void AddThing(BaseThing *);
    void AddThingAfterThis(BaseThing *);
    void DisplayThings(ThingRenderData *);
    void EffectsThings(ThingRenderData *);
    void EnableActions(i32, i32, i32);
    void EnterLevelThings(ThingLevelData *);
    void ExitLevelThings(ThingLevelData *);
    void ProcessThings(ThingProcessData *);
    void RemoveDependanciesThings(ThingRemoveData *);
    void RemoveTemporaryThings();
    void RenderThings(ThingRenderData *);
    void ResetThings(ThingResetData *);
    ThingManager(i32);
    void cbEdTimingSelect(eduimenu_s *, eduiitem_s *, u32);
    void cbEdTrackCancel(eduimenu_s *, eduimenu_s *);
    void edTimingEnter();
    void edTimingInit();
    void edTimingProc(float, nupad_s *);
    void edTimingRender();
};
struct VirtualControlButton {
    void Process(float);
    void Render();
    VirtualControlButton(NuVec2 const &, float, MechInputTouchMainController::eButtonTypes);
};
struct VirtualControlButtonMover {
    void Process(float);
    VirtualControlButtonMover(MechInputTouchVirtualConsoleController &);
};
struct VirtualControlDPad {
    void Process(float);
    void Render();
    VirtualControlDPad(NuVec2 const &, float, MechInputTouchVirtualConsoleController &);
    virtual ~VirtualControlDPad();
};
struct VirtualControlDPad_LockButton {
    void Process(float);
    void Render();
    VirtualControlDPad_LockButton(VirtualControlDPad &);
};

#endif // LEGOAPI_TYPES_H