#!/usr/bin/env python3
"""Extract named ELF data symbols as C byte arrays.

Usage: extract_elf_symbols.py INPUT OUTPUT SYMBOL [SYMBOL ...]

The checked-in Android binary retains a symbol table, so this utility can
recover embedded assets (for example the platform shader strings) without
hard-coding file offsets.  GNU readelf and nm are used deliberately so the
script does not require a third-party ELF module.
"""

from __future__ import annotations

import argparse
import pathlib
import re
import subprocess


def command(*args: str) -> str:
    return subprocess.check_output(args, text=True)


def load_sections(binary: pathlib.Path) -> list[tuple[int, int, int]]:
    sections: list[tuple[int, int, int]] = []
    pattern = re.compile(
        r"^\s*\[\s*\d+\]\s+\S+\s+\S+\s+([0-9a-fA-F]+)\s+([0-9a-fA-F]+)\s+([0-9a-fA-F]+)"
    )
    for line in command("readelf", "-SW", str(binary)).splitlines():
        match = pattern.match(line)
        if match:
            address, offset, size = (int(value, 16) for value in match.groups())
            sections.append((address, offset, size))
    return sections


def load_symbols(binary: pathlib.Path) -> dict[str, tuple[int, int]]:
    symbols: dict[str, tuple[int, int]] = {}
    pattern = re.compile(r"^([0-9a-fA-F]+)\s+([0-9a-fA-F]+)\s+\S\s+(.+)$")
    for line in command("nm", "-S", str(binary)).splitlines():
        match = pattern.match(line)
        if match:
            address, size, name = match.groups()
            symbols[name] = (int(address, 16), int(size, 16))
    return symbols


def file_offset(sections: list[tuple[int, int, int]], address: int, size: int) -> int:
    for section_address, section_offset, section_size in sections:
        if section_address <= address and address + size <= section_address + section_size:
            return section_offset + address - section_address
    raise ValueError(f"symbol range {address:#x}..{address + size:#x} is not file-backed")


def emit_array(name: str, data: bytes) -> str:
    lines = [f"static const unsigned char {name}[] = {{"]
    for start in range(0, len(data), 16):
        chunk = ", ".join(f"0x{value:02x}" for value in data[start : start + 16])
        lines.append(f"    {chunk},")
    lines.append("};")
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("input", type=pathlib.Path)
    parser.add_argument("output", type=pathlib.Path)
    parser.add_argument("symbols", nargs="+")
    args = parser.parse_args()

    sections = load_sections(args.input)
    symbols = load_symbols(args.input)
    image = args.input.read_bytes()
    arrays: list[str] = ["// Generated by scripts/extract_elf_symbols.py; do not edit."]
    for name in args.symbols:
        if name not in symbols:
            raise ValueError(f"ELF symbol not found: {name}")
        address, size = symbols[name]
        offset = file_offset(sections, address, size)
        arrays.append(emit_array(name, image[offset : offset + size]))
    args.output.write_text("\n\n".join(arrays) + "\n")


if __name__ == "__main__":
    main()
