#!/usr/bin/env python3
"""Render the interactive GitHub Pages map from matching.json.

The input is generated by scripts/generate_bazel_objdiff_report.py and already
contains original addresses/sizes, whole-binary objdiff scores, and Bazel
translation-unit ownership.
"""

from __future__ import annotations

import argparse
import json
import math
import os
from pathlib import Path
import sys


def _all_functions(data):
    """Flatten unit-grouped, ambiguous, and unassigned function records."""
    functions = []
    for unit in data.get("units", []):
        for function in unit.get("functions", []):
            functions.append({**function, "unit": unit["name"], "ambiguous": False})
    for function in data.get("ambiguous_functions", []):
        functions.append({**function, "unit": None, "ambiguous": True})
    for function in data.get("unassigned_functions", []):
        functions.append({**function, "unit": None, "ambiguous": False})
    return sorted(functions, key=lambda item: (item["address"], item["name"]))


def build_unit_spans(text_start, text_size, functions):
    """Return address-ordered unit runs, including inter-function padding."""
    text_end = text_start + text_size
    ranges = []
    for function in functions:
        start = max(function["address"], text_start)
        end = min(function["address"] + function["size"], text_end)
        unit = None if function["ambiguous"] else function["unit"]
        if end > start:
            ranges.append((start, end, unit))

    clusters = []
    for start, end, unit in sorted(ranges):
        if clusters and start < clusters[-1][1]:
            cluster_start, cluster_end, owners = clusters[-1]
            clusters[-1] = (
                cluster_start,
                max(cluster_end, end),
                owners | ({unit} if unit is not None else set()),
            )
        else:
            clusters.append((start, end, {unit} if unit is not None else set()))

    spans = []
    current = None
    for start, end, owners in clusters:
        unit = next(iter(owners)) if len(owners) == 1 else None
        if current is not None and unit == current[0]:
            current = (current[0], current[1], max(current[2], end))
            continue
        if current is not None:
            spans.append((current[0], current[1], max(current[2], start)))
            current = None
        if unit is not None:
            current = (unit, start, end)
    if current is not None:
        spans.append(current)
    return spans


def build_payload(data, row_bytes, cell_bytes):
    """Convert the documented matching JSON into the compact browser payload."""
    text_start = data["text"]["address"]
    text_size = data["text"]["size"]
    text_end = text_start + text_size
    functions = _all_functions(data)
    unit_spans = build_unit_spans(text_start, text_size, functions)
    unit_names = sorted({function["unit"] for function in functions if function["unit"]})
    unit_ids = {name: index for index, name in enumerate(unit_names)}

    function_data = []
    for function in functions:
        start = max(function["address"], text_start)
        end = min(function["address"] + function["size"], text_end)
        if end <= start:
            continue
        function_data.append(
            {
                "a": start - text_start,
                "s": end - start,
                "n": function["demangled_name"],
                "r": function["name"],
                "u": unit_ids.get(function["unit"], -1),
                "p": function["match_percent"],
                "x": function["ambiguous"],
            }
        )

    span_data = [
        {"a": start - text_start, "s": end - start, "u": unit_ids[unit]}
        for unit, start, end in unit_spans
    ]
    return {
        "metrics": {
            "fuzzyMatchPercent": data["measures"]["fuzzy_match_percent"],
            "matchedFunctions": data["measures"]["matched_functions"],
            "totalFunctions": data["measures"]["total_functions"],
            "matchedCodePercent": data["measures"]["matched_code_percent"],
            "bazelUnits": data["summary"]["bazel_units"],
        },
        "sections": [
            {
                "n": section["name"],
                "a": section["address"],
                "s": section["size"],
                "k": section["kind"],
            }
            for section in data["sections"]
        ],
        "textStart": text_start,
        "textSize": text_size,
        "rowBytes": row_bytes,
        "cellBytes": cell_bytes,
        "rows": math.ceil(text_size / row_bytes),
        "units": unit_names,
        "functions": function_data,
        "spans": span_data,
    }


HTML_TEMPLATE_PATH = Path(__file__).with_name("plot_binary_match_map.html")


COI_SERVICE_WORKER = r"""if (typeof window === "undefined") {
  self.addEventListener("install", () => self.skipWaiting());
  self.addEventListener("activate", event => event.waitUntil(self.clients.claim()));
  self.addEventListener("fetch", event => {
    if (event.request.cache === "only-if-cached" && event.request.mode !== "same-origin") return;
    event.respondWith(fetch(event.request).then(response => {
      if (response.status === 0) return response;
      const headers = new Headers(response.headers);
      headers.set("Cross-Origin-Embedder-Policy", "require-corp");
      headers.set("Cross-Origin-Opener-Policy", "same-origin");
      headers.set("Cross-Origin-Resource-Policy", "same-origin");
      return new Response(response.body, {
        status: response.status,
        statusText: response.statusText,
        headers,
      });
    }));
  });
} else if (!window.crossOriginIsolated && "serviceWorker" in navigator) {
  navigator.serviceWorker.register("./coi-serviceworker.js").then(() => {
    if (!navigator.serviceWorker.controller) {
      navigator.serviceWorker.addEventListener("controllerchange", () => location.reload(), {once: true});
    }
  });
}
"""



def render_html(payload, template_path=HTML_TEMPLATE_PATH):
    encoded = json.dumps(payload, separators=(",", ":"), ensure_ascii=True)
    template = template_path.read_text(encoding="utf-8")
    return template.replace("/*__DATA__*/", encoded.replace("</", "<\\/"))


def generate_site(report_path, output_path, row_bytes, cell_bytes):
    with report_path.open(encoding="utf-8") as report_file:
        data = json.load(report_file)
    if data.get("schema_version") != 1:
        raise ValueError("unsupported or missing schema_version")
    payload = build_payload(data, row_bytes, cell_bytes)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with output_path.open("w", encoding="utf-8") as output_file:
        output_file.write(render_html(payload))
    with (output_path.parent / "coi-serviceworker.js").open(
        "w", encoding="utf-8"
    ) as service_worker_file:
        service_worker_file.write(COI_SERVICE_WORKER)
    (output_path.parent / ".nojekyll").touch()
    return payload


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "report",
        nargs="?",
        default="matching.json",
        help="custom matching data (default: matching.json)",
    )
    parser.add_argument(
        "-o",
        "--output",
        default="doc/pages/index.html",
        help="output HTML (default: doc/pages/index.html)",
    )
    parser.add_argument(
        "--bytes-per-cell",
        type=int,
        default=512,
        help="address bytes represented by a cell (default: 512)",
    )
    parser.add_argument(
        "--columns",
        type=int,
        default=256,
        help="fallback cells per row before viewport sizing (default: 256)",
    )
    args = parser.parse_args()

    if args.bytes_per_cell < 1 or args.columns < 1:
        parser.error("--bytes-per-cell and --columns must be at least 1")

    workspace = Path(os.environ.get("BUILD_WORKSPACE_DIRECTORY", Path.cwd()))
    report_path = Path(args.report)
    if not report_path.is_absolute():
        report_path = workspace / report_path
    output_path = Path(args.output)
    if not output_path.is_absolute():
        output_path = workspace / output_path

    try:
        row_bytes = args.columns * args.bytes_per_cell
        payload = generate_site(
            report_path, output_path, row_bytes, args.bytes_per_cell
        )
    except (KeyError, OSError, TypeError, ValueError, json.JSONDecodeError) as error:
        print(f"error: {error}", file=sys.stderr)
        return 1

    print(
        f"Mapped {len(payload['functions'])} functions in "
        f"{len(payload['units'])} units with {len(payload['spans'])} spans "
        f"to {output_path}"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
