#include <stddef.h>

#include "globals.h"
#include "nu2api/nu3d/nucamera.h"
#include "nu2api/nucore/common.h"
#include "nu2api/nusound/nusound.h"
#include "legoapi/core/input/timer.h"

void *PlayerItemType = 0;
i32 PLAYERITEMTYPECOUNT = 0;

i32 PAL = 0;
f32 FRAMETIME = 0;
f32 DEFAULTFPS = 0;
f32 DEFAULTFRAMETIME = 0;
f32 MAXFRAMETIME = 0;

i32 SUPERBUFFERSIZE = 0x2EB8EEB;
VARIPTR permbuffer_base;
VARIPTR original_permbuffer_base;
VARIPTR superbuffer_end;
VARIPTR permbuffer_ptr;
VARIPTR permbuffer_end;

char prodcode[16] = {0};
char *iconname = "lego.ico";
char unicodename[64] = "LEGO Star Wars Saga";

i32 EPISODECOUNT = 0;
i32 AREACOUNT = 0;
GAMESAVE_s Game = {0};
i32 COMPLETIONPOINTS = 0;
i32 POINTS_PER_CHARACTER = 0;
i32 POINTS_PER_SUPERBONUSCOMPLETE = 0;
i32 POINTS_PER_TIMETRIAL = 0;
i32 POINTS_PER_STORY = 0;
i32 POINTS_PER_CHALLENGE = 0;
i32 POINTS_PER_MINIKIT = 0;
i32 POINTS_PER_TRUEJEDI = 0;
i32 POINTS_PER_REDBRICK = 0;
i32 POINTS_PER_MISSION = 0;
i32 POINTS_PER_CHEAT = 0;
i32 POINTS_PER_GOLDBRICK = 0;
i32 BOTHTRUEJEDIGOLDBRICKS = 0;
i32 SHOPGOLDBRICKS = 0;
i32 GOLDBRICKFORSUPERBONUS = 0;
i32 GOLDBRICKFORSUPERSTORY = 0;
i32 GOLDBRICKFORCHALLENGE = 0;
i32 POINTS_PER_SUPERSTORY = 0;
i32 GOLDBRICKPOINTS = 0;

i32 CompletionPointInfo[7] = {0};

NUSOUND_FILENAME_INFO *MusicInfo = NULL;
NUSOUND_FILENAME_INFO *g_music = NULL;
u8 g_BackgroundUsedFogColour = 0;
u32 SFX_MUSIC_COUNT = 0;

NUCAMERA *pNuCam = NULL;

i32 NOSOUND = 0;

const char *theEmptyString = "";

ANativeWindow *g_appWindow = NULL;

char g_deviceManufacturer[256] = {0};
char g_deviceModel[256] = {0};

i32 g_forceSysMemVbs = 0;

i32 g_forceETC1 = 0;

i32 g_isLowestEndDevice = 0;
i32 g_isLowEndDevice = 0;
i32 g_isMidRangeDevice = 0;
i32 g_lowEndLevelBehaviour = 0;

f32 DoubleScoreTime = 0.0f;
f32 GameTimer[2] = {0.0f, 0.0f};
i32 AreaGlobals = 0;

i32 BonusWinner = 0;
i32 BonusWinFlag = 0;
i32 ChallengeMode = 0;
TIMER ChallengeTimer;
i32 HIGHGAMEOBJECT = 0;
void *Obj = NULL;
f32 AreaPickupGravity = 0.0f;

i32 LevObjRef_FirstObj = 0;
i32 LevObjRef_LastObj = 0;
i32 LevObjRef_FirstRefObj = 0;

LEVELOBJECT *ObjTabList = NULL;
i32 LEVELOBJECTCOUNT = 0;
i32 LEVELOBJECTMAX = 0;
i32 EXTRALEVELOBJECTCOUNT = 0;

char *ExtraLevelObject_NameTable = NULL;
i32 ExtraLevelObject_NameTableSize = 0;
i32 ExtraLevelObject_NameTableIndex = 0;

LEVELDATA *NewLData = NULL;
LEVELDATA *HUB_LDATA = NULL;
i32 grab_screen_image = 0;
i32 FreePlay = 0;
i32 waiting_for_new_level = 0;

void *LevelProgressData = NULL;

GameAnimSysProgress gameanimsysprogress = {0, 0, NULL};

nufpcomjmp_s *Level_ConfigBeforeLoad_GameKeywords = NULL;
nufpcomjmp_s *Level_ConfigAfterLoad_GameKeywords = NULL;

u32 EXBLOWUPFLAGS = 0;

i32 BeenAttacked = 0;

i32 last_area = -1;
LEVELDATA *LastLData = NULL;
LEVELDATA *TITLES_LDATA = NULL;
LEVELDATA *STATUS_LDATA = NULL;
LEVELDATA *ASTEROIDCHASEMITRO_LDATA = NULL;
LEVELDATA *BOUNTYHUNTERPURSUITE_LDATA = NULL;
LEVELDATA *CLOUDCITYESCAPEB_LDATA = NULL;
LEVELDATA *CLOUDCITYTRAPOUTRO_LDATA = NULL;
LEVELDATA *CRUISERB_LDATA = NULL;
LEVELDATA *CRUISERE_LDATA = NULL;
LEVELDATA *CRUISERG_LDATA = NULL;
LEVELDATA *DAGOBAHD_LDATA = NULL;
LEVELDATA *DEATHSTAR2BATTLEB_LDATA = NULL;
LEVELDATA *DEATHSTAR2BATTLEMIDTRO_LDATA = NULL;
LEVELDATA *DEATHSTARBATTLEA_LDATA = NULL;
LEVELDATA *DEATHSTARBATTLEB_LDATA = NULL;
LEVELDATA *DEATHSTARRESCUEA_LDATA = NULL;
LEVELDATA *DEATHSTARRESCUED_LDATA = NULL;
LEVELDATA *DEATHSTARRESCUEE_LDATA = NULL;
LEVELDATA *DOGFIGHTA_LDATA = NULL;
LEVELDATA *DOOKUOUTRO_LDATA = NULL;
LEVELDATA *E1CHARACTERBONUSA_LDATA = NULL;
LEVELDATA *E2VEHICLEBONUSA_LDATA = NULL;
LEVELDATA *ENDORBATTLEB_LDATA = NULL;
LEVELDATA *ENDORBATTLEC_LDATA = NULL;
LEVELDATA *ENDORBATTLED_LDATA = NULL;
LEVELDATA *FACTORYD_LDATA = NULL;
LEVELDATA *FACTORYF_LDATA = NULL;
LEVELDATA *GUNGAN_B_LDATA = NULL;
LEVELDATA *HOTHBATTLEB_LDATA = NULL;
LEVELDATA *HOTHBATTLED_LDATA = NULL;
LEVELDATA *HOTHBATTLEOUTRO_LDATA = NULL;
LEVELDATA *JABBASPALACE_OUTRO_LDATA = NULL;
LEVELDATA *JEDI_OUTRO_LDATA = NULL;
LEVELDATA *KAMINOC_LDATA = NULL;
LEVELDATA *MOSEISLEYC_LDATA = NULL;
LEVELDATA *NEGOTIATIONSC_LDATA = NULL;
LEVELDATA *PODRACEOUTRO1_LDATA = NULL;
LEVELDATA *PODRACESTATUS_LDATA = NULL;
LEVELDATA *RETAKEB_LDATA = NULL;
LEVELDATA *RETAKEINTRO1_LDATA = NULL;
LEVELDATA *RETAKEINTRO2_LDATA = NULL;
LEVELDATA *RETAKEINTRO3_LDATA = NULL;
LEVELDATA *SENATEA_LDATA = NULL;
LEVELDATA *TATOOINEC_LDATA = NULL;
LEVELDATA *TATOOINEE_LDATA = NULL;
LEVELDATA *TEMPLEB_LDATA = NULL;
LEVELDATA *TEMPLESTATUS_LDATA = NULL;

void *LevelHackData = NULL;
void *OldLevelHackData = NULL;
i32 LevelHackSize = 0;
i32 LevelHackSendTimer = 0;
i32 new_level_from_menu = 0;
i32 BGLOAD = 0;

i32 Reflections_On = 1;
i32 disable_narrow_socks = 0;
i32 script_spline_selected = 0;
f32 character_farclip = 0.0f;
i32 LevMusicAction = 0;
i32 LevMusicAmbient = 0;
i32 LevMusicOtherAction = 0;
i32 LevMusicOtherAmbient = 0;
u32 ResetBits = 0;

i32 reset_restart = 0;
i32 newlevelfrommenu_newmenuid = -1;
i32 newlevelfrommenu_newmenuy = -1;
i32 NextArea_FreePlay = 0;
