# set optimization levels
set_source_files_properties(${CMAKE_CURRENT_SOURCE_DIR}/src/gameapi/ai/aisys/aiscript.cpp PROPERTIES COMPILE_OPTIONS "-O3")
set_source_files_properties(${CMAKE_CURRENT_SOURCE_DIR}/src/gameapi/ai/aisys/aistate.cpp PROPERTIES COMPILE_OPTIONS "-O3")

set_source_files_properties(${CMAKE_CURRENT_SOURCE_DIR}/src/gameapi/edtools/edfile.cpp PROPERTIES COMPILE_OPTIONS "-O3")

set_source_files_properties(${CMAKE_CURRENT_SOURCE_DIR}/src/gameapi/gui/apimenu.cpp PROPERTIES COMPILE_OPTIONS "-O3")

set_source_files_properties(${CMAKE_CURRENT_SOURCE_DIR}/src/gamelib/NewTerrain.cpp PROPERTIES COMPILE_OPTIONS "-O2")

set_source_files_properties(${CMAKE_CURRENT_SOURCE_DIR}/src/gamelib/crc/crc.cpp PROPERTIES COMPILE_OPTIONS "-O3")

set_source_files_properties(${CMAKE_CURRENT_SOURCE_DIR}/src/gamelib/nuwind/nuwind.cpp PROPERTIES COMPILE_OPTIONS "-O3")

set_source_files_properties(${CMAKE_CURRENT_SOURCE_DIR}/src/legoapi/world/area.cpp PROPERTIES COMPILE_OPTIONS "-O3")
set_source_files_properties(${CMAKE_CURRENT_SOURCE_DIR}/src/legoapi/gizmo/base/gizmo.cpp PROPERTIES COMPILE_OPTIONS "-O3")
set_source_files_properties(${CMAKE_CURRENT_SOURCE_DIR}/src/legoapi/world/level.cpp PROPERTIES COMPILE_OPTIONS "-O3")
set_source_files_properties(${CMAKE_CURRENT_SOURCE_DIR}/src/legoapi/core/input/qrand.cpp PROPERTIES COMPILE_OPTIONS "-O3")
set_source_files_properties(${CMAKE_CURRENT_SOURCE_DIR}/src/legoapi/characters/core/players.cpp PROPERTIES COMPILE_OPTIONS "-O2")
set_source_files_properties(${CMAKE_CURRENT_SOURCE_DIR}/src/legoapi/core/config/cheats.cpp PROPERTIES COMPILE_OPTIONS "-O3")
set_source_files_properties(${CMAKE_CURRENT_SOURCE_DIR}/src/legoapi/items/base/collection.cpp PROPERTIES COMPILE_OPTIONS "-O3")
set_source_files_properties(${CMAKE_CURRENT_SOURCE_DIR}/src/legoapi/props/doors/door.cpp PROPERTIES COMPILE_OPTIONS "-O3")
set_source_files_properties(${CMAKE_CURRENT_SOURCE_DIR}/src/legoapi/episodes/episode.cpp PROPERTIES COMPILE_OPTIONS "-O3")
set_source_files_properties(${CMAKE_CURRENT_SOURCE_DIR}/src/legoapi/core/input/timer.cpp PROPERTIES COMPILE_OPTIONS "-O3")
set_source_files_properties(${CMAKE_CURRENT_SOURCE_DIR}/src/legoapi/world/world.cpp PROPERTIES COMPILE_OPTIONS "-O3")
set_source_files_properties(${CMAKE_CURRENT_SOURCE_DIR}/src/legoapi/world/mission.cpp PROPERTIES COMPILE_OPTIONS "-O3")
set_source_files_properties(${CMAKE_CURRENT_SOURCE_DIR}/src/legoapi/world/missions.cpp PROPERTIES COMPILE_OPTIONS "-O3")

set_source_files_properties(${CMAKE_CURRENT_SOURCE_DIR}/src/legoapi/gizmos/trigger/ai.cpp PROPERTIES COMPILE_OPTIONS "-O3")
set_source_files_properties(${CMAKE_CURRENT_SOURCE_DIR}/src/legoapi/gizmos/trigger/gizaimessage.cpp PROPERTIES COMPILE_OPTIONS "-O3")
set_source_files_properties(${CMAKE_CURRENT_SOURCE_DIR}/src/legoapi/gizmos/traps/attractos.cpp PROPERTIES COMPILE_OPTIONS "-O3")
set_source_files_properties(${CMAKE_CURRENT_SOURCE_DIR}/src/legoapi/gizmos/door/door.cpp PROPERTIES COMPILE_OPTIONS "-O3")
set_source_files_properties(${CMAKE_CURRENT_SOURCE_DIR}/src/legoapi/gizmos/fx/edgizshadowmachine.cpp PROPERTIES COMPILE_OPTIONS "-O3")
set_source_files_properties(${CMAKE_CURRENT_SOURCE_DIR}/src/legoapi/gizmos/traps/gizbombgen.cpp PROPERTIES COMPILE_OPTIONS "-O3")
set_source_files_properties(${CMAKE_CURRENT_SOURCE_DIR}/src/legoapi/gizmos/object/gizbuildits.cpp PROPERTIES COMPILE_OPTIONS "-O3")
set_source_files_properties(${CMAKE_CURRENT_SOURCE_DIR}/src/legoapi/gizmos/traps/gizforce.cpp PROPERTIES COMPILE_OPTIONS "-O3")
set_source_files_properties(${CMAKE_CURRENT_SOURCE_DIR}/src/legoapi/gizmos/object/gizpanel.cpp PROPERTIES COMPILE_OPTIONS "-O3")
set_source_files_properties(${CMAKE_CURRENT_SOURCE_DIR}/src/legoapi/gizmos/fx/gizmopickups.cpp PROPERTIES COMPILE_OPTIONS "-O3")
set_source_files_properties(${CMAKE_CURRENT_SOURCE_DIR}/src/legoapi/gizmos/object/gizobstacles.cpp PROPERTIES COMPILE_OPTIONS "-O3")
set_source_files_properties(${CMAKE_CURRENT_SOURCE_DIR}/src/legoapi/gizmos/transport/gizportal.cpp PROPERTIES COMPILE_OPTIONS "-O3")
set_source_files_properties(${CMAKE_CURRENT_SOURCE_DIR}/src/legoapi/gizmos/trigger/gizrandom.cpp PROPERTIES COMPILE_OPTIONS "-O3")
set_source_files_properties(${CMAKE_CURRENT_SOURCE_DIR}/src/legoapi/gizmos/trigger/gizspecial.cpp PROPERTIES COMPILE_OPTIONS "-O3")
set_source_files_properties(${CMAKE_CURRENT_SOURCE_DIR}/src/legoapi/gizmos/trigger/giztimer.cpp PROPERTIES COMPILE_OPTIONS "-O3")
set_source_files_properties(${CMAKE_CURRENT_SOURCE_DIR}/src/legoapi/gizmos/traps/giztorpmachine.cpp PROPERTIES COMPILE_OPTIONS "-O3")
set_source_files_properties(${CMAKE_CURRENT_SOURCE_DIR}/src/legoapi/gizmos/traps/gizturrets.cpp PROPERTIES COMPILE_OPTIONS "-O3")
set_source_files_properties(${CMAKE_CURRENT_SOURCE_DIR}/src/legoapi/gizmos/transport/grapples.cpp PROPERTIES COMPILE_OPTIONS "-O3")
set_source_files_properties(${CMAKE_CURRENT_SOURCE_DIR}/src/legoapi/gizmos/fx/guidelines.cpp PROPERTIES COMPILE_OPTIONS "-O3")
set_source_files_properties(${CMAKE_CURRENT_SOURCE_DIR}/src/legoapi/gizmos/object/hatmachine.cpp PROPERTIES COMPILE_OPTIONS "-O3")
set_source_files_properties(${CMAKE_CURRENT_SOURCE_DIR}/src/legoapi/gizmos/transport/ledges.cpp PROPERTIES COMPILE_OPTIONS "-O3")
set_source_files_properties(${CMAKE_CURRENT_SOURCE_DIR}/src/legoapi/gizmos/object/lever.cpp PROPERTIES COMPILE_OPTIONS "-O3")
set_source_files_properties(${CMAKE_CURRENT_SOURCE_DIR}/src/legoapi/gizmos/trigger/minicut.cpp PROPERTIES COMPILE_OPTIONS "-O3")
set_source_files_properties(${CMAKE_CURRENT_SOURCE_DIR}/src/legoapi/gizmos/object/newblowup.cpp PROPERTIES COMPILE_OPTIONS "-O3")
set_source_files_properties(${CMAKE_CURRENT_SOURCE_DIR}/src/legoapi/gizmos/door/plugs.cpp PROPERTIES COMPILE_OPTIONS "-O3")
set_source_files_properties(${CMAKE_CURRENT_SOURCE_DIR}/src/legoapi/gizmos/door/push.cpp PROPERTIES COMPILE_OPTIONS "-O3")
set_source_files_properties(${CMAKE_CURRENT_SOURCE_DIR}/src/legoapi/gizmos/door/securitydoors.cpp PROPERTIES COMPILE_OPTIONS "-O3")
set_source_files_properties(${CMAKE_CURRENT_SOURCE_DIR}/src/legoapi/gizmos/traps/shards.cpp PROPERTIES COMPILE_OPTIONS "-O3")
set_source_files_properties(${CMAKE_CURRENT_SOURCE_DIR}/src/legoapi/gizmos/trigger/signals.cpp PROPERTIES COMPILE_OPTIONS "-O3")
set_source_files_properties(${CMAKE_CURRENT_SOURCE_DIR}/src/legoapi/gizmos/door/spinner.cpp PROPERTIES COMPILE_OPTIONS "-O3")
set_source_files_properties(${CMAKE_CURRENT_SOURCE_DIR}/src/legoapi/gizmos/object/technos.cpp PROPERTIES COMPILE_OPTIONS "-O3")
set_source_files_properties(${CMAKE_CURRENT_SOURCE_DIR}/src/legoapi/gizmos/transport/teleport.cpp PROPERTIES COMPILE_OPTIONS "-O3")
set_source_files_properties(${CMAKE_CURRENT_SOURCE_DIR}/src/legoapi/gizmos/transport/tightropes.cpp PROPERTIES COMPILE_OPTIONS "-O3")
set_source_files_properties(${CMAKE_CURRENT_SOURCE_DIR}/src/legoapi/gizmos/transport/tubes.cpp PROPERTIES COMPILE_OPTIONS "-O3")
set_source_files_properties(${CMAKE_CURRENT_SOURCE_DIR}/src/legoapi/gizmos/door/zipups.cpp PROPERTIES COMPILE_OPTIONS "-O3")
set_source_files_properties(${CMAKE_CURRENT_SOURCE_DIR}/src/legoapi/core/config/cheat.cpp PROPERTIES COMPILE_OPTIONS "-O3;-fPIE")
set_source_files_properties(${CMAKE_CURRENT_SOURCE_DIR}/src/nu2api/nu3d/NuRenderDevice.cpp PROPERTIES COMPILE_OPTIONS "-O2")
set_source_files_properties(${CMAKE_CURRENT_SOURCE_DIR}/src/nu2api/nu3d/nuscreen.cpp PROPERTIES COMPILE_OPTIONS "-O2")
set_source_files_properties(${CMAKE_CURRENT_SOURCE_DIR}/src/nu2api/nu3d/nugscn.cpp PROPERTIES COMPILE_OPTIONS "-O3")
set_source_files_properties(${CMAKE_CURRENT_SOURCE_DIR}/src/nu2api/nu3d/numtl.cpp PROPERTIES COMPILE_OPTIONS "-O3")
set_source_files_properties(${CMAKE_CURRENT_SOURCE_DIR}/src/nu2api/nu3d/nuportal.cpp PROPERTIES COMPILE_OPTIONS "-O3")
set_source_files_properties(${CMAKE_CURRENT_SOURCE_DIR}/src/nu2api/nu3d/nuspline.c PROPERTIES COMPILE_OPTIONS "-O3")
set_source_files_properties(${CMAKE_CURRENT_SOURCE_DIR}/src/nu2api/nu3d/nuqfnt.cpp PROPERTIES COMPILE_OPTIONS "-O2")
set_source_files_properties(${CMAKE_CURRENT_SOURCE_DIR}/src/nu2api/nu3d/nurndr.cpp PROPERTIES COMPILE_OPTIONS "-O3")
set_source_files_properties(${CMAKE_CURRENT_SOURCE_DIR}/src/nu2api/nu3d/nushader.cpp PROPERTIES COMPILE_OPTIONS "-O3")
set_source_files_properties(${CMAKE_CURRENT_SOURCE_DIR}/src/nu2api/nu3d/nutex.cpp PROPERTIES COMPILE_OPTIONS "-O3")
set_source_files_properties(${CMAKE_CURRENT_SOURCE_DIR}/src/nu2api/nu3d/nuvport.cpp PROPERTIES COMPILE_OPTIONS "-O3")

set_source_files_properties(${CMAKE_CURRENT_SOURCE_DIR}/src/nu2api/nu3d/android/numtl_android.cpp PROPERTIES COMPILE_OPTIONS "-O2")
set_source_files_properties(${CMAKE_CURRENT_SOURCE_DIR}/src/nu2api/nu3d/android/nuqfnt_android.cpp PROPERTIES COMPILE_OPTIONS "-O2")
set_source_files_properties(${CMAKE_CURRENT_SOURCE_DIR}/src/nu2api/nu3d/android/nurenderthread.cpp PROPERTIES COMPILE_OPTIONS "-O3")
set_source_files_properties(${CMAKE_CURRENT_SOURCE_DIR}/src/nu2api/nu3d/android/nutex_ios_ex.cpp PROPERTIES COMPILE_OPTIONS "-O3")

set_source_files_properties(${CMAKE_CURRENT_SOURCE_DIR}/src/nu2api/nu3d/generic/nucamera_gen.cpp PROPERTIES COMPILE_OPTIONS "-O2")

set_source_files_properties(${CMAKE_CURRENT_SOURCE_DIR}/src/nu2api/nuandroid/ios_graphics.cpp PROPERTIES COMPILE_OPTIONS "-O2")

set_source_files_properties(${CMAKE_CURRENT_SOURCE_DIR}/src/nu2api/nucore/NuInputDevice.cpp PROPERTIES COMPILE_OPTIONS "-O2")
set_source_files_properties(${CMAKE_CURRENT_SOURCE_DIR}/src/nu2api/nucore/NuInputManager.cpp PROPERTIES COMPILE_OPTIONS "-O2")
set_source_files_properties(${CMAKE_CURRENT_SOURCE_DIR}/src/nu2api/nucore/NuMemoryManager.cpp PROPERTIES COMPILE_OPTIONS "-O2")
set_source_files_properties(${CMAKE_CURRENT_SOURCE_DIR}/src/nu2api/nucore/NuMemoryPool.cpp PROPERTIES COMPILE_OPTIONS "-O2")
set_source_files_properties(${CMAKE_CURRENT_SOURCE_DIR}/src/nu2api/nucore/NuThreadManager.cpp PROPERTIES COMPILE_OPTIONS "-O2")
set_source_files_properties(${CMAKE_CURRENT_SOURCE_DIR}/src/nu2api/nucore/NuVirtualTouchDevice.cpp PROPERTIES COMPILE_OPTIONS "-O3")
set_source_files_properties(${CMAKE_CURRENT_SOURCE_DIR}/src/nu2api/nucore/deflate.cpp PROPERTIES COMPILE_OPTIONS "-O3")
set_source_files_properties(${CMAKE_CURRENT_SOURCE_DIR}/src/nu2api/nucore/nucore.cpp PROPERTIES COMPILE_OPTIONS "-O2")
set_source_files_properties(${CMAKE_CURRENT_SOURCE_DIR}/src/nu2api/nucore/numemory.cpp PROPERTIES COMPILE_OPTIONS "-O2")
set_source_files_properties(${CMAKE_CURRENT_SOURCE_DIR}/src/nu2api/nucore/nupad_interface.cpp PROPERTIES COMPILE_OPTIONS "-O3")
set_source_files_properties(${CMAKE_CURRENT_SOURCE_DIR}/src/nu2api/nucore/nunew.cpp PROPERTIES COMPILE_OPTIONS "-O2")
set_source_files_properties(${CMAKE_CURRENT_SOURCE_DIR}/src/nu2api/nucore/nustring.cpp PROPERTIES COMPILE_OPTIONS "-O3")

set_source_files_properties(${CMAKE_CURRENT_SOURCE_DIR}/src/nu2api/nucore/android/NuInputDevice_android.cpp PROPERTIES COMPILE_OPTIONS "-O2")
set_source_files_properties(${CMAKE_CURRENT_SOURCE_DIR}/src/nu2api/nucore/android/NuThread_android.cpp PROPERTIES COMPILE_OPTIONS "-O3")
set_source_files_properties(${CMAKE_CURRENT_SOURCE_DIR}/src/nu2api/nucore/android/bgproc_android.cpp PROPERTIES COMPILE_OPTIONS "-O2")
set_source_files_properties(${CMAKE_CURRENT_SOURCE_DIR}/src/nu2api/nucore/android/numemory_android.cpp PROPERTIES COMPILE_OPTIONS "-O2")

set_source_files_properties(${CMAKE_CURRENT_SOURCE_DIR}/src/nu2api/nufile/nufile.c PROPERTIES COMPILE_OPTIONS "-O2")
set_source_files_properties(${CMAKE_CURRENT_SOURCE_DIR}/src/nu2api/nufile/nufilebase.cpp PROPERTIES COMPILE_OPTIONS "-O2")
set_source_files_properties(${CMAKE_CURRENT_SOURCE_DIR}/src/nu2api/nufile/tmclient.cpp PROPERTIES COMPILE_OPTIONS "-O3")

set_source_files_properties(${CMAKE_CURRENT_SOURCE_DIR}/src/nu2api/nufile/android/nufile_android.cpp PROPERTIES COMPILE_OPTIONS "-O2")

set_source_files_properties(${CMAKE_CURRENT_SOURCE_DIR}/src/nu2api/numusic/numusic.cpp PROPERTIES COMPILE_OPTIONS "-O2")

set_source_files_properties(${CMAKE_CURRENT_SOURCE_DIR}/src/nu2api/nuplatform/nuplatform.cpp PROPERTIES COMPILE_OPTIONS "-O3")

set_source_files_properties(${CMAKE_CURRENT_SOURCE_DIR}/src/nu2api/nusound/nusound_loader.cpp PROPERTIES COMPILE_OPTIONS "-O3")
set_source_files_properties(${CMAKE_CURRENT_SOURCE_DIR}/src/nu2api/nusound/nusound_loader_ogg.cpp PROPERTIES COMPILE_OPTIONS "-O3")
set_source_files_properties(${CMAKE_CURRENT_SOURCE_DIR}/src/nu2api/nusound/nusound_decoder.cpp PROPERTIES COMPILE_OPTIONS "-O3")
set_source_files_properties(${CMAKE_CURRENT_SOURCE_DIR}/src/nu2api/nusound/nusound_sample.cpp PROPERTIES COMPILE_OPTIONS "-O3")
set_source_files_properties(${CMAKE_CURRENT_SOURCE_DIR}/src/nu2api/nusound/nusound3_include.cpp PROPERTIES COMPILE_OPTIONS "-O3")
set_source_files_properties(${CMAKE_CURRENT_SOURCE_DIR}/src/nu2api/nusound/nusound_buffer.cpp PROPERTIES COMPILE_OPTIONS "-O3")
set_source_files_properties(${CMAKE_CURRENT_SOURCE_DIR}/src/nu2api/nusound/nusound_streamer.cpp PROPERTIES COMPILE_OPTIONS "-O2")
set_source_files_properties(${CMAKE_CURRENT_SOURCE_DIR}/src/nu2api/nusound/nusound_memorymanager.cpp PROPERTIES COMPILE_OPTIONS "-O3")
set_source_files_properties(${CMAKE_CURRENT_SOURCE_DIR}/src/nu2api/nusound/nusound_system.cpp PROPERTIES COMPILE_OPTIONS "-O3")
set_source_files_properties(${CMAKE_CURRENT_SOURCE_DIR}/src/nu2api/nusound/nusound_voice.cpp PROPERTIES COMPILE_OPTIONS "-O3")
set_source_files_properties(${CMAKE_CURRENT_SOURCE_DIR}/src/nu2api/nusound/nusound_weakptr.cpp PROPERTIES COMPILE_OPTIONS "-O3")

# link platform-specific dependencies
add_ogg_vorbis()
add_squish()
target_link_libraries(saga PRIVATE custom_ogg_vorbis)
target_link_libraries(saga PRIVATE custom_squish)
target_link_libraries(saga PRIVATE GLESv2 EGL)
