name: Linux i686 build

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    build:
        runs-on: ubuntu-latest
        container: ubuntu:questing
        steps:
            - uses: actions/checkout@v4

            - name: Install requirements
              run: >
                  sudo dpkg --add-architecture i386 &&
                  sudo apt-get -y update &&
                  sudo apt-get install wget gcc-multilib g++-multilib libgles2-mesa-dev:i386 libvorbis-dev:i386 libsquish-dev:i386

            # add Ubuntu 25.10 questing mirror to get SDL3 packages
            - name: Install SDL3
              run: >
                  echo "deb http://archive.ubuntu.com/ubuntu/ questing universe" | sudo tee /etc/apt/sources.list.d/questing.list &&
                  sudo apt-get -y update &&
                  sudo apt-get install libsdl3-dev:i386

            - name: Install CMake 4.x
              uses: lukka/get-cmake@latest

            - name: Configure CMake
              run: cmake -B build -DBUILD_FOR_HOST=ON .
              env:
                  PKG_CONFIG_PATH: /usr/lib/i386-linux-gnu/pkgconfig

            - name: Build
              run: cmake --build build --verbose
