name: MSYS2 Windows build

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    build:
        runs-on: windows-latest

        steps:
            - uses: actions/checkout@v4

            - name: Setup MSYS2
              uses: msys2/setup-msys2@v2
              with:
                  msystem: UCRT64
                  update: true
                  install: base-devel mingw-w64-ucrt-x86_64-make mingw-w64-ucrt-x86_64-pkgconf mingw-w64-ucrt-x86_64-gcc mingw-w64-ucrt-x86_64-cmake mingw-w64-ucrt-x86_64-libvorbis mingw-w64-ucrt-x86_64-gles-headers mingw-w64-ucrt-x86_64-angleproject mingw-w64-ucrt-x86_64-sdl3

            - name: Fix angle
              shell: msys2 {0}
              run: |-
                cat << 'EOF' > /ucrt64/lib/pkgconfig/glesv2.pc
                prefix=/ucrt64
                exec_prefix=${prefix}
                libdir=${exec_prefix}/lib
                includedir=${prefix}/include

                Name: glesv2
                Description: ANGLE OpenGL ES 2.0 library
                Version: 2.0
                Libs: -L${libdir} -lGLESv2
                Cflags: -I${includedir}
                EOF

            - name: Cache Android NDK
              uses: actions/cache@v4
              with:
                  path: ndk
                  key: android-ndk-r8e

            - name: Cache vorbis
              uses: actions/cache@v4
              with:
                  path: libs/ogg-vorbis
                  key: vorbis-${{ hashFiles('**/CMakeLists.txt') }}

            - name: Configure CMake
              shell: msys2 {0}
              run: cmake -B build-host -DBUILD_FOR_HOST=ON -DCMAKE_CXX_FLAGS="-Duint=\"unsigned int\" -Wno-return-type -include wincompat.h -static-libgcc -static-libstdc++"

            - name: Build
              shell: msys2 {0}
              run: cmake --build build-host --verbose
