name: Linux i686 build

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Install requirements
              run: >
                  sudo dpkg --add-architecture i386 &&
                  sudo apt-get -y update &&
                  sudo apt-get install git wget gcc-multilib g++-multilib libgles2-mesa-dev:i386 libvorbis-dev:i386

            - name: Build SDL3
              run: >
                  git clone git@github.com:libsdl-org/SDL.git &&
                  cd SDL &&
                  git checkout release-3.4.2 &&
                  mkdir build &&
                  cmake -S . -B build &&
                  cmake --build . &&
                  sudo cmake --install .
              env:
                  CC: i686-linux-gnu-gcc
                  CXX: i686-linux-gnu-g++
                  AR: i686-linux-gnu-ar
                  RANLIB: i686-linux-gnu-ranlib
                  PKG_CONFIG: i686-linux-gnu-pkg-config

            - name: Install CMake 4.x
              uses: lukka/get-cmake@latest

            - name: Configure CMake
              run: cmake -B build -DBUILD_FOR_HOST=ON .
              env:
                  PKG_CONFIG_PATH: /usr/lib/i386-linux-gnu/pkgconfig

            - name: Build
              run: cmake --build build --verbose
