name: objdiff report check

on:
    pull_request:
    push:
        branches:
            - main

permissions:
    contents: read

jobs:
    objdiff-diff:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v7
              with:
                  fetch-depth: 0

            - name: Check report exists
              run: test -f report.json

            - name: Compare objdiff reports
              env:
                  # PR -> actual PR base SHA
                  # Push -> previous commit SHA
                  BASE_SHA: ${{ github.event.pull_request.base.sha || github.event.before }}
              run: |
                  git show ${{ env.BASE_SHA }}:report.json > report_old.json
                  {
                    echo 'report<<EOF'
                    python scripts/objdiffdiff.py report.json report_old.json
                    echo 'EOF'
                  } >> "$GITHUB_OUTPUT"
              id: objdiff-diff

            - name: Comment on PR
              if: github.event_name == 'pull_request'
              uses: mshick/add-pr-comment@v3
              with:
                  message: |
                      ## Objdiff Diff Report

                      between `${{ github.event.pull_request.base.sha }}` and `${{ github.sha }}`

                      ${{ steps.objdiff-diff.outputs.report }}
